version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: extjs-example-nginx
    ports:
      - 81:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.confg
      - ./:/usr/share/nginx/html
